# This is a basic workflow to help you get started with Actions

name: first
env:
  FILENAME: test1
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test-python:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
      # setup python
      - name: Setup python
        uses: actions/setup-python@v2
      # Test  
      - name: Test script
        run: python hello.py

  Create-artifact:
    needs: [Test-python]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
      # create python artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: .
